server:
  port: 3000
spring:
  application:
    name: atguigu-crowd-redis
  redis:
    host: 8.131.50.70
    password: 113220
    timeout: 60s
eureka:
  client:
    service-url:
     defaultZone: http://localhost:1000/eureka